package com.crypto.dashboard.domain;

public enum VerificationType {
    EMAIL_VERIFICATION,
    PHONE_VERIFICATION,
    IDENTITY_VERIFICATION,
    ADDRESS_VERIFICATION,
    BANK_ACCOUNT_VERIFICATION,
    CRYPTO_WALLET_VERIFICATION,
    SOCIAL_MEDIA_VERIFICATION,
    DOCUMENT_VERIFICATION,
    TWO_FACTOR_AUTHENTICATION
}
