spring.application.name=dashboard




spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/crypto_dashboard
spring.datasource.username=root
spring.datasource.password=Keerti1@3
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

spring.username=admin
spring.password=password